services:
  db:
    image: postgres:14
    restart: always
    command: postgres -c timezone=Asia/Kolkata
    environment:
      TZ: Asia/Kolkata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password_here
      POSTGRES_DB: daily_planner
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      TZ: Asia/Kolkata
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: your_password_here
      DB_NAME: daily_planner
      EMAIL_USER: jenifermj06062003@gmail.com
      EMAIL_PASS: "nhxe xroo kkki ftnu"

volumes:
  pgdata:
